---
title: "phyloR"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{phyloR}
  %\VignetteEngine{knitr::rmarkdown}
  %\vignetteCoding{UTF-8}
---


# Introduction

The phyloR package provides functions for retrieving gene sequences and phylogenetic analysis

  
```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


## Installing phyloR

You can install phyloR from GitHub.

To install from GitHub:

```{r install-github-devtools, eval=FALSE}
remotes::install_github("libcell/phyloR")

```

##Loading the phhyloR
```{r setup, include=FALSE}
library(phyloR)  

```
## Example

Here are some example using the main function of phyloR:

```{r examples1}
taxinfo1 <- get_orthologs(gene_id = "K00161",
                          id.type = "ko_id",
                          species.list = "Homo sapiens",
                          species.type = "scientificname")
taxinfo2 <- get_orthologs(gene_id = "5160",
                          id.type = "ncbi_id",
                          species.list = "hsa",
                          species.type = "abbspname")
taxinfo3 <- get_orthologs(gene_id = "hsa:5160",
                          id.type = "kegg_id",
                          species.list = "9606",
                          species.type = "taxonomic_id")
```

```{r examples2}
seq_set1 <- get_kegg_sequences(gene_ids = "K00161",
                               id.type = "ko_id",
                               seq.type = "DNA",
                               species.list = c("hsa", "ptr"),
                               species.type = "abbspname")
seq_set2 <- get_kegg_sequences(gene_ids = c("5160", "465525"),
                               id.type = "ncbi_id")
seq_set3 <- get_kegg_sequences(gene_ids = c("hsa:5160", "ptr:465525"),
                               id.type = "kegg_id",
                               seq.type = "DNA")
```

```{r examples3}
DNA_seq <- system.file("extdata", "DNA_sequences.fas", package = "phyloR")
align_trim(DNA_seq, seq.type = "DNA", method = "ClustalW")

protein_seq <- system.file("extdata", "protein_sequences.fas", package = "phyloR")
align_trim(protein_seq, seq.type = "protein", method = "ClustalW")

```

```{r examples4}
DNA_seq <- system.file("extdata", "DNA_seq.fas", package = "phyloR")
tree1 <- gene_tree(seq.file = DNA_seq,
                   seq.type = "DNA",
                   tree_method = "UPGMA")

protein_seq <- system.file("extdata", "protein_seq.fas", package = "phyloR")
tree2 <- gene_tree(seq.file = protein_seq,
                   seq.type = "protein",
                   tree_method = "NJ")
```

```{r examples5}
dna <- c("K01939", "K03644", "K00797", "K00927", "K00088", "K02257", "K00164",
         "K00820", "K06158", "K00008")
data_dir <- system.file("extdata", "sequences", package = "phyloR")
tree1 <- concat_tree(seq.file = dna,
                     seq.type = "DNA",
                     data_dir = data_dir,
                     tree_method = "NJ")
tree2 <- concat_tree(seq.file = dna,
                     seq.type = "DNA",
                     data_dir = data_dir,
                     tree_method = "UPGMA")
```

```{r examples6}
dna <- c("K01939", "K03644", "K00797", "K00927", "K00088", "K02257", "K00164",
         "K00820", "K06158", "K00008")
data_dir <- system.file("extdata", "sequences", package = "phyloR")
tree1 <- coalescent_tree(seq.file = dna,
                         seq.type = "protein",
                         data_dir = data_dir,
                         tree_method = "NJ",
                         show_tree = TRUE)
tree2 <- coalescent_tree(seq.file = dna,
                         seq.type = "DNA",
                         data_dir = data_dir,
                         tree_method = "UPGMA")

```

```{r example7}
tree <- gene_tree_fetch(gene_id = "K00826",
                        species.list = c("hsa", "sce", "dme", "cel",         
                                         "xla", "gga", "ssc", "rno",
                                         "mmu", "mcc", "gmx", "bta",
                                         "ece", "zma", "osa", "ath"),
                        species.type = "abbspname",
                        seq.type = "DNA",
                        tree_method = "NJ",
                        show_tree = TRUE)
```

```{r example8}
tree <- concat_tree_fetch(gene_ids = c("K00820", "K00088", "K00927",
                                       "K06158", "K00008","K00164",
                                       "K00797", "K01939", "K02257",
                                       "K03644"),
                          id.type = "ko_id",
                          species.list = c("ath", "gmx", "zma", "osa",
                                           "dme", "cel", "mmu", "rno",
                                           "hsa", "mcc", "ssc", "bta",
                                           "gga", "xla", "sce", "ece"),
                          species.type = "abbspname",
                          seq.type = "DNA",
                          tree_method = "UPGMA")
```

```{r example9}
tree <- coalescent_tree_fetch(gene_ids = c("K00820", "K00088", "K00927",
                                           "K06158", "K00008", "K00164",
                                           "K00797", "K01939", "K02257",
                                           "K03644"),
                              id.type = "ko_id",
                              species.list = c("ath", "gmx", "zma", "osa",
                                               "dme", "cel", "mmu", "rno",
                                               "hsa", "mcc", "ssc", "bta",
                                               "gga", "xla", "sce", "ece"),
                              species.type = "abbspname",
                              seq.type = "DNA",
                              tree_method = "NJ")
```

```{r examples10}
species1 <- c("Homo sapiens", "Pan troglodytes", "Mus musculus",
              "Rattus norvegicus","Canis lupus familiaris", "Felis catus")
tree1 <- species_tree(species = species1, species.type = "scientificname")

species2 <- c("9606", "9598", "10090", "9615", "9685", "10116")
tree2 <- species_tree(species = species2, species.type = "taxonomic_id")

species3 = c("ath", "gmx", "zma", "osa",
             "dme", "cel", "mmu", "rno",
             "hsa", "mcc", "ssc", "bta",
             "gga", "xla", "sce", "ece")
tree3 <- species_tree(species = species3, species.type = "abbspname")

```

```{r exxample11}
DNA_seq <- system.file("extdata", "DNA_seq.fas", package = "phyloR")
tree1 <- gene_tree(seq.file = DNA_seq,
                   seq.type = "DNA",
                   tree_method = "UPGMA")
species = c("ath", "gmx", "zma", "osa",
            "dme", "cel", "mmu", "rno",
            "hsa", "mcc", "ssc", "bta",
            "gga", "xla", "sce", "ece")
tree2 <- species_tree(species = species, species.type = "abbspname")
relation <- compare_trees(tree1, tree2)

```
